version: "3.9"
   
services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=menu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - django_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=menu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  django_db: