# Generated by Django 4.1.2 on 2022-10-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(0, 'BackEnd Developer'), (1, 'FrontEnd Developer'), (2, 'Mobile Developer'), (3, 'DevOps'), (4, 'QA')], default=0),
        ),
    ]
