# Generated by Django 4.1.2 on 2022-10-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
